### ISSUE TITLE
Access other page content on current_page

### ISSUE THREAD

**Issue by anthonylebrun** [smashingboxes/cardboard-admin-archive#5]
``` YAML
pages:
  about_us:
    parts:
      initiatives:
        page_slug: string
        repeatable: true
```

We have a list of page titles and extracts on one page with a link to those respective pages. It would be nice to have some kind of helper to do Page.find(:page_slug) to access parts and fields of other pages.
